# Generated by Django 6.0.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='kafka_offset',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
